# Generated by Django 3.2.9 on 2021-12-30 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_account_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='phone_number',
            field=models.IntegerField(default=0),
        ),
    ]
